version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - mine

  gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - mine

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - ":3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - mine

  api:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - ":3030"
    networks:
      - mine


networks:
  mine: