version: '3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  gateway:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    command: nginx -g "daemon off;"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000

  api:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
